videotheque_film:
    resource: "@VideothequeFilmBundle/Resources/config/routing.yml"
    prefix:   /film

videotheque_core:
    resource: "@VideothequeCoreBundle/Resources/config/routing.yml"
    prefix:   /

